OpenTokDemo/Models/Session.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace OpenTokDemo.Models
{
    public class Session
    {
        public string id { get; set; }
        public string token { get; set; }
        [DataType(DataType.DateTime)]
        [Required]
        public DateTime timeExpired { get; set; }
    }
    public class SessionContext:DbContext
    {
        public DbSet<Session> Sessions { get; set; }
    }
}

OpenTokDemo/Controllers/HomeController.cs
using OpenTokDemo.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OpenTokDemo.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {

            return View();
        }
        [HttpPost]
        public ActionResult Index(Session session)
        {
            using(var context=new SessionContext())
            {
                session=context.Sessions.Find(session.id);
            }
            if (session != null)
                return View("StartTok", session);
            return View();
        }
        

        

        
    }
}

OpenTokDemo/Controllers/SessionController.cs
using OpenTok;
using OpenTokDemo.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace OpenTokDemo.Controllers
{
    public class SessionController : Controller
    {
        public ActionResult Index()
        {
            using (var context = new SessionContext())
            {

                var model = context.Sessions.ToList();
                return View(model);
            }
        }
        public ActionResult Delete(string id)
        {
            using (var context = new SessionContext())
            {

                var session = context.Sessions.First(s=>s.id==id);
                
                return View(session);
            }
           
        }
        [HttpPost]
        public ActionResult Delete(Session trash)
        {
            using (var context = new SessionContext())
            {
                trash = context.Sessions.Find(trash.id);
                context.Sessions.Remove(trash);
                context.SaveChanges();
                var model = context.Sessions.ToList();
                return View("Index", model);
            }
            

        }
        
        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Add(Session newSession)
        {
            if (ModelState.IsValid)
            {
                OpenTokSDK opentok = new OpenTokSDK();
                Dictionary<string, object> options = new Dictionary<string, object>();
                options.Add(SessionPropertyConstants.P2P_PREFERENCE, "enabled");
                string sessionId = opentok.CreateSession(Request.ServerVariables["REMOTE_ADDR"], options);
                Dictionary<string, object> tokenOptions = new Dictionary<string, object>();
                tokenOptions.Add(TokenPropertyConstants.EXPIRE_TIME, newSession.timeExpired);
                tokenOptions.Add(TokenPropertyConstants.ROLE, RoleConstants.SUBSCRIBER);
                string token = opentok.GenerateToken(sessionId,tokenOptions);
                
                using (var context = new SessionContext())
                {
                    newSession.id = sessionId;
                    newSession.token = token;
                    context.Sessions.Add(newSession);
                    context.SaveChanges();
                    var model = context.Sessions.ToList();
                    return View("Index", model);

                }
            }
            else
                return View();
        }
        [HttpPost]
        public JsonResult GetSessionDitails(string id)
        {
            Session session;
            using (var context = new SessionContext())
            {
                session = context.Sessions.Find(id);   
            }
            return Json(session);
        }
	}
}

OpenTokDemo/Views/Home/Index.cshtml
@model OpenTokDemo.Models.Session

@{
    ViewBag.Title = "Index";
}

<h2>Rozpocznij rozmowę</h2>

<div id="container">
    <h4>Wprowadź id sesji.</h4>
	<hr />
        <input type="text" id="sessionid"  />
        <div class="form-actions no-color">
        <input type="submit" value="Rozpocznij rozmowę" class="btn btn-default" id="submitid" /> 
           
        </div>

</div>
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/opentok")

OpenTokDemo/Views/Session/Add.cshtml
@model OpenTokDemo.Models.Session

@{
    ViewBag.Title = "Add";
}

<h2>Add</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Session</h4>
        
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.timeExpired, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.timeExpired)
                @Html.ValidationMessageFor(model => model.timeExpired, "Podaj datę w formacie rrrr-mm-dd hh:mm");
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

OpenTokDemo/Views/Session/Delete.cshtml
@model OpenTokDemo.Models.Session

@{
    ViewBag.Title = "Delete";
}

<h2>Usuń</h2>

<h3>Czy na pewno chcesz usunąć?</h3>
<div>
    <h4>Sesja</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.timeExpired)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.timeExpired)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Usuń!" class="btn btn-default" /> |
            @Html.ActionLink("Powrót", "Index")
        </div>
    }
</div>

OpenTokDemo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OpenTok - Demo</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("OpenTokDemo", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Lista sesji", "Index", "Session")</li>
                    <li>@Html.ActionLink("Dodaj sesję", "Add", "Session")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>